import yaml
import rosco.toolbox
import os
from rosco.toolbox.ofTools.util.FileTools import load_yaml

def write_types(yfile):
    '''
    Writes ROSCO_types.f90
    -- All additions to the types should be added to rosco_types.yaml!

    Parameters:
    -----------
    yfile: string
            path to rosco_types.yaml
    '''
    reg = load_yaml(yfile)
    reg.pop('default_types')
    registry_fname = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'src','ROSCO_Types.f90')
    file = open(registry_fname, 'w')
    # Header
    file.write('! ROSCO Registry\n')
    file.write('! This file is automatically generated by write_registry.py using ROSCO v{}\n'.format(rosco.toolbox.__version__))
    file.write('! For any modification to the registry, please edit the rosco_types.yaml accordingly\n \n')
    file.write('MODULE ROSCO_Types\n') 
    file.write('USE, INTRINSIC :: ISO_C_Binding\n')
    file.write('USE Constants\n')
    file.write('IMPLICIT NONE\n')
    file.write('\n')
    file.write(f"Character(*), PARAMETER     :: rosco_version = '{rosco.toolbox.__version__}'             ! ROSCO version\n")
    file.write('\n')
    # Loop Types
    for toptype in reg.keys():
        file.write('TYPE, PUBLIC :: {}\n'.format(toptype))
        for attype in reg[toptype].keys():
            f90type = read_type(reg[toptype][attype])
            atstr  =  check_size(reg[toptype], attype)
            if reg[toptype][attype]['equals'] is not None:
                atstr += ' = ' + str(reg[toptype][attype]['equals'])
            file.write('    {:<25s}     :: {:<25s}   ! {}\n'.format(f90type, atstr, reg[toptype][attype]['description']))
        file.write('END TYPE {}\n'.format(toptype))
        file.write('\n')
    file.write('END MODULE ROSCO_Types\n')
    file.close()

def write_roscoio(yfile):
    '''
    Writes ROSCO_IO.f90
    -- All additions to the types should be added to rosco_types.yaml!

    Parameters:
    -----------
    yfile: string
            path to rosco_types.yaml
    '''
    reg = load_yaml(yfile)
    reg.pop('default_types')
    registry_fname = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'src','ROSCO_IO.f90')
    file = open(registry_fname, 'w')
    file.write('! ROSCO IO\n')
    file.write('! This file is automatically generated by write_registry.py using ROSCO v{}\n'.format(rosco.toolbox.__version__))
    file.write('! For any modification to the registry, please edit the rosco_types.yaml accordingly\n \n')
    file.write('MODULE ROSCO_IO\n') 
    file.write('    USE, INTRINSIC :: ISO_C_Binding\n')
    file.write('    USE ROSCO_Types\n')
    file.write('    USE ReadSetParameters\n')
    file.write('    USE Constants\n')
    file.write('IMPLICIT NONE\n\n')
    file.write('CONTAINS\n\n')
    # ------------------------------------------------
    # ------------ WriteRestartFile ------------------
    # ------------------------------------------------
    file.write('SUBROUTINE WriteRestartFile(LocalVar, CntrPar, ErrVar, objInst, RootName, size_avcOUTNAME)\n')
    file.write("    TYPE(LocalVariables), INTENT(IN)                :: LocalVar\n")
    file.write("    TYPE(ControlParameters), INTENT(INOUT)          :: CntrPar\n")
    file.write("    TYPE(ObjectInstances), INTENT(INOUT)            :: objInst\n")
    file.write("    TYPE(ErrorVariables), INTENT(INOUT)             :: ErrVar\n")
    file.write("    INTEGER(IntKi), INTENT(IN)                      :: size_avcOUTNAME\n")
    file.write("    CHARACTER(size_avcOUTNAME), INTENT(IN)        :: RootName \n")
    file.write("    \n")
    file.write("    INTEGER(IntKi)               :: Un                  ! I/O unit for pack/unpack (checkpoint & restart)\n")
    file.write("    INTEGER(IntKi)               :: I                   ! Generic index.\n")
    file.write("    CHARACTER(128)               :: InFile              ! Input checkpoint file\n")
    file.write("    INTEGER(IntKi)               :: ErrStat\n")
    file.write("    CHARACTER(128)               :: ErrMsg              \n")
    file.write("    CHARACTER(128)               :: n_t_global          ! timestep number as a string\n")
    file.write("\n")
    file.write("    WRITE(n_t_global, '(I0.0)' ) NINT(LocalVar%Time/LocalVar%DT)\n")
    file.write("    InFile = TRIM(RootName)//TRIM( n_t_global )//'.RO.chkp'\n")
    file.write("    CALL GetNewUnit(Un, ErrVar)\n")
    file.write("    OPEN(unit=Un, FILE=TRIM(InFile), STATUS='UNKNOWN', FORM='UNFORMATTED' , ACCESS='STREAM', IOSTAT=ErrStat, ACTION='WRITE' )\n")
    file.write("\n")
    file.write("    IF ( ErrStat /= 0 ) THEN\n")
    file.write("        ErrVar%aviFAIL = 1\n")
    file.write("        ErrVar%ErrMsg  = 'ROSCO_IO: Cannot open checkpoint file '//TRIM(InFile)//' for writing'\n")
    file.write("\n")
    file.write("    ELSE\n")

    # Loop Variable Tree
    for var in reg['LocalVariables']:
        if reg['LocalVariables'][var]['type'] == 'derived_type':
            for dvar in reg[reg['LocalVariables'][var]['id']]:
                file.write('        WRITE( Un, IOSTAT=ErrStat) LocalVar%{}%{}\n'.format(var,dvar))
        elif reg['LocalVariables'][var]['size'] > 0:
            for i in range(reg['LocalVariables'][var]['size']):
                file.write('        WRITE( Un, IOSTAT=ErrStat) LocalVar%{}({})\n'.format(var, i+1))
        else:
            file.write('        WRITE( Un, IOSTAT=ErrStat) LocalVar%{}\n'.format(var))
    for var in reg['ObjectInstances']:
        file.write('        WRITE( Un, IOSTAT=ErrStat) objInst%{}\n'.format(var))
    file.write('        Close ( Un )\n')
    file.write("        IF ( ErrStat /= 0 ) THEN\n")
    file.write("            ErrVar%aviFAIL = 1\n")
    file.write("            ErrVar%ErrMsg  = 'ROSCO_IO: Error writing checkpoint file.'\n")
    file.write("        ENDIF\n")
    file.write('    ENDIF\n')
    file.write('END SUBROUTINE WriteRestartFile\n')
    file.write('\n \n')
    # ------------------------------------------------
    # ------------ ReadRestartFile ------------------
    # ------------------------------------------------
    file.write('SUBROUTINE ReadRestartFile(avrSWAP, LocalVar, CntrPar, objInst, PerfData, RootName, size_avcOUTNAME, ErrVar)\n')
    file.write("    TYPE(LocalVariables), INTENT(INOUT)             :: LocalVar\n")
    file.write("    TYPE(ControlParameters), INTENT(INOUT)          :: CntrPar\n")
    file.write("    TYPE(ObjectInstances), INTENT(INOUT)            :: objInst\n")
    file.write("    TYPE(PerformanceData), INTENT(INOUT)            :: PerfData\n")
    file.write("    TYPE(ErrorVariables), INTENT(INOUT)             :: ErrVar\n")
    file.write("    REAL(ReKi), INTENT(IN)                          :: avrSWAP(*)\n")
    file.write("    INTEGER(IntKi), INTENT(IN)                      :: size_avcOUTNAME\n")
    file.write("    CHARACTER(size_avcOUTNAME), INTENT(IN)        :: RootName \n")
    file.write("    \n")
    file.write("    INTEGER(IntKi)               :: Un                  ! I/O unit for pack/unpack (checkpoint & restart)\n")
    file.write("    INTEGER(IntKi)               :: I                   ! Generic index.\n")
    file.write("    CHARACTER(128)               :: InFile              ! Input checkpoint file\n")
    file.write("    INTEGER(IntKi)               :: ErrStat\n")
    file.write("    CHARACTER(128)               :: ErrMsg              \n")
    file.write("    CHARACTER(128)               :: n_t_global          ! timestep number as a string\n")
    file.write("\n")
    file.write("    WRITE(n_t_global, '(I0.0)' ) NINT(avrSWAP(2)/avrSWAP(3))\n")
    file.write("    InFile = TRIM(RootName)//TRIM( n_t_global )//'.RO.chkp'\n")
    file.write("    CALL GetNewUnit(Un, ErrVar)\n")
    file.write("    OPEN(unit=Un, FILE=TRIM(InFile), STATUS='UNKNOWN', FORM='UNFORMATTED' , ACCESS='STREAM', IOSTAT=ErrStat, ACTION='READ' )\n")
    file.write("\n")
    file.write("    IF ( ErrStat /= 0 ) THEN\n")
    file.write("        ErrVar%aviFAIL = 1\n")
    file.write("        ErrVar%ErrMsg  = 'ROSCO_IO: Cannot open checkpoint file '//TRIM(InFile)//' for reading'\n")
    file.write("\n")
    file.write("    ELSE\n")

    # Loop Variable Tree
    for var in reg['LocalVariables']:
        if reg['LocalVariables'][var]['type'] == 'derived_type':
            for dvar in reg[reg['LocalVariables'][var]['id']]:
                file.write('        READ( Un, IOSTAT=ErrStat) LocalVar%{}%{}\n'.format(var, dvar))
        elif reg['LocalVariables'][var]['size'] > 0:
            for i in range(reg['LocalVariables'][var]['size']):
                file.write('        READ( Un, IOSTAT=ErrStat) LocalVar%{}({})\n'.format(var, i+1))
        else:
            file.write('        READ( Un, IOSTAT=ErrStat) LocalVar%{}\n'.format(var))
            if var == 'ACC_INFILE_SIZE':
                file.write('        ALLOCATE(LocalVar%ACC_INFILE(LocalVar%ACC_INFILE_SIZE))\n')
    for var in reg['ObjectInstances']:
        file.write('        READ( Un, IOSTAT=ErrStat) objInst%{}\n'.format(var))
    file.write('        Close ( Un )\n')
    file.write("        IF ( ErrStat /= 0 ) THEN\n")
    file.write("            ErrVar%aviFAIL = 1\n")
    file.write("            ErrVar%ErrMsg  = 'ROSCO_IO: Error reading checkpoint file.'\n")
    file.write("        ENDIF\n")
    file.write('    ENDIF\n')
    file.write('    ! Read Parameter files\n')
    file.write('    CALL ReadControlParameterFileSub(CntrPar, LocalVar, LocalVar%ACC_INFILE, LocalVar%ACC_INFILE_SIZE, RootName, ErrVar)\n')
    file.write('    IF (CntrPar%WE_Mode > 0) THEN\n')
    file.write('        CALL READCpFile(CntrPar, PerfData, ErrVar)\n')
    file.write('    ENDIF\n')
    file.write('END SUBROUTINE ReadRestartFile\n')
    file.write('\n \n')
    # ------------------------------------------------
    
    
    # Get LocalVar info for definitions
    # -- Always prints blade(1) for multi-bladed inputss (e.g. BldPitch(1))
    lv_strings = []
    for lv_idx, localvar in enumerate(reg['LocalVariables']):
        if reg['LocalVariables'][localvar]['type'] in ['integer', 'real', 'complex']:
            lv_strings.append(localvar)

    n_lv_outputs = len(lv_strings)
    
    # ------------------ Debug -----------------------
    # ------------------------------------------------
    file.write('SUBROUTINE Debug(LocalVar, CntrPar, DebugVar, ErrVar, avrSWAP, RootName, size_avcOUTNAME)\n')
    file.write('! Debug routine, defines what gets printed to DEBUG.dbg if LoggingLevel = 1\n')
    file.write('\n')
    file.write('    TYPE(ControlParameters), INTENT(IN) :: CntrPar\n')
    file.write('    TYPE(LocalVariables), INTENT(IN) :: LocalVar\n')
    file.write('    TYPE(DebugVariables), INTENT(IN) :: DebugVar\n')
    file.write('    TYPE(ErrorVariables),       INTENT(INOUT)   :: ErrVar\n')
    file.write('\n')
    file.write('    INTEGER(IntKi), INTENT(IN)      :: size_avcOUTNAME\n')
    file.write('    INTEGER(IntKi)                  :: I , nDebugOuts, nLocalVars   ! Generic index.\n')
    file.write('    CHARACTER(1), PARAMETER         :: Tab = CHAR(9)                ! The tab character.\n')
    file.write('    CHARACTER(100)                  :: FmtDat                       ! The format of the debugging data\n')
    file.write('    INTEGER(IntKi), SAVE            :: UnDb                         ! I/O unit for the debugging information\n')
    file.write('    INTEGER(IntKi), SAVE            :: UnDb2                        ! I/O unit for the debugging information, avrSWAP\n')
    file.write('    INTEGER(IntKi), SAVE            :: UnDb3                        ! I/O unit for the debugging information, avrSWAP\n')
    file.write('    REAL(ReKi), INTENT(INOUT)       :: avrSWAP(*)                   ! The swap array, used to pass data to, and receive data from, the DLL controller.\n')
    file.write('    CHARACTER(size_avcOUTNAME), INTENT(IN) :: RootName            ! a Fortran version of the input C string (not considered an array here)    [subtract 1 for the C null-character]\n')
    file.write('    CHARACTER(200)                  :: Version                      ! git version of ROSCO\n')
    file.write('    CHARACTER(15), ALLOCATABLE      :: DebugOutStrings(:), DebugOutUnits(:)\n')
    file.write('\n')
    file.write('    ! Avr output writing\n')
    file.write('    INTEGER(IntKi), SAVE, DIMENSION(:), ALLOCATABLE     :: avrIndices\n')
    file.write('    INTEGER(IntKi)                  :: avrBaseLength = 85\n')
    file.write('    INTEGER(IntKi)                  :: Ind\n')
    file.write('    CHARACTER(100)                  :: avrFmt\n')
    file.write('\n')
    file.write('    REAL(DbKi), ALLOCATABLE         :: DebugOutData(:)\n \n')
    file.write(f'    CHARACTER(15), DIMENSION({n_lv_outputs})      :: LocalVarOutStrings\n')
    file.write('    REAL(DbKi), ALLOCATABLE         :: LocalVarOutData(:)\n \n')
    file.write('    nDebugOuts = {}\n'.format(len(reg['DebugVariables'].keys())))
    file.write('    Allocate(DebugOutData(nDebugOuts))\n')
    file.write('    Allocate(DebugOutStrings(nDebugOuts))\n')
    file.write('    Allocate(DebugOutUnits(nDebugOuts))\n')
    dbg_strings = []
    dbg_units   = []
    
    # Print Debug variables
    for dbg_idx, dbgvar in enumerate(reg['DebugVariables']):
        dbg_strings.append(dbgvar)
        desc = reg['DebugVariables'][dbgvar]['description']
        dbg_units.append(desc[desc.find('['):desc.find(']')+1])
        file.write('    DebugOutData({}) = DebugVar%{}\n'.format(dbg_idx+1,dbgvar))
    file.write('    DebugOutStrings = [CHARACTER(15) :: ')
    counter = 0
    for string in dbg_strings:
        counter += 1
        if counter == len(dbg_strings):
            file.write(" '{}'".format(string))
        else:
            file.write(" '{}',".format(string))
        if (counter % 5 == 0):
            file.write(' & \n                                     ')
    file.write(']\n')
    file.write('    DebugOutUnits = [CHARACTER(15) :: ')
    counter = 0
    for unit in dbg_units:
        # Give dummy unit if not defined
        if not unit:
            unit = '[N/A]'
        counter += 1
        if counter == len(dbg_units):
            file.write(" '{}'".format(unit))    # last line
        else:
            file.write(" '{}',".format(unit))
        if (counter % 5 == 0):      # group in groups of 5
            file.write(' & \n                                     ')
    file.write(']\n')

    # Print Local Variables 

    file.write('    nLocalVars = {}\n'.format(n_lv_outputs))
    file.write('    Allocate(LocalVarOutData(nLocalVars))\n')

    # Loop through LocalVariables
    for lv_idx, localvar in enumerate(lv_strings):
        # If an array, only show first
        if reg['LocalVariables'][localvar]['size'] > 0 or reg['LocalVariables'][localvar]['allocatable']:
            file.write('    LocalVarOutData({}) = LocalVar%{}(1)\n'.format(lv_idx+1, localvar))
        else:
            file.write('    LocalVarOutData({}) = LocalVar%{}\n'.format(lv_idx+1, localvar))
    file.write('\n')
    for i_string, string in enumerate(lv_strings):
        file.write(f"    LocalVarOutStrings({i_string+1}) = '{string}'\n")

    
    # Debug file initialization 
    # -- iStatus = 0 on first call, iStatus = -9 in restart
    file.write("    ! Initialize debug file\n")
    file.write("    IF ((LocalVar%iStatus == 0) .OR. (LocalVar%iStatus == -9))  THEN ! .TRUE. if we're on the first call to the DLL\n")
    # Standar debug
    file.write("        IF (CntrPar%LoggingLevel > 0) THEN\n")
    file.write("            CALL GetNewUnit(UnDb, ErrVar)\n")
    file.write("            OPEN(unit=UnDb, FILE=TRIM(RootName)//'.RO.dbg')\n")
    file.write("            WRITE(UnDb, *)  'Generated on '//CurDate()//' at '//CurTime()//' using ROSCO-'//TRIM(rosco_version)\n")
    file.write("            WRITE(UnDb, '(99(a20,TR5:))') 'Time',   DebugOutStrings\n")
    file.write("            WRITE(UnDb, '(99(a20,TR5:))') '(sec)',  DebugOutUnits\n")
    file.write("        END IF\n")
    file.write("\n")
    # LocalVar debug
    file.write("        IF (CntrPar%LoggingLevel > 1) THEN\n")
    file.write("            CALL GetNewUnit(UnDb2, ErrVar)\n")
    file.write("            OPEN(unit=UnDb2, FILE=TRIM(RootName)//'.RO.dbg2')\n")
    file.write("            WRITE(UnDb2, *)  'Generated on '//CurDate()//' at '//CurTime()//' using ROSCO-'//TRIM(rosco_version)\n")
    file.write(f"            WRITE(UnDb2, '({n_lv_outputs+1}(a20,TR5:))') 'Time',   LocalVarOutStrings\n")
    file.write(f"            WRITE(UnDb2, '({n_lv_outputs+1}(a20,TR5:))')\n")
    file.write("        END IF\n")
    file.write("\n")
    # avrSWAP debug
    file.write("        IF (CntrPar%LoggingLevel > 2) THEN\n")
    file.write("            ! Set avrIndices, start with basic indices\n")
    file.write("            Allocate(avrIndices(avrBaseLength))\n")
    file.write("            DO Ind = 1, avrBaseLength\n")
    file.write("                avrIndices(Ind) = Ind\n")
    file.write("            END DO\n")
    file.write("\n")
    file.write("            ! Cable control indices\n")
    file.write("            IF (CntrPar%CC_Mode > 0) THEN\n")
    file.write("                DO Ind = 1, SIZE(CntrPar%CC_GroupIndex)\n")
    file.write("                    Call AddToList(avrIndices,CntrPar%CC_GroupIndex(Ind))\n")
    file.write("                    Call AddToList(avrIndices,CntrPar%CC_GroupIndex(Ind)+1)\n")
    file.write("                END DO\n")
    file.write("            END IF\n")
    file.write("\n")
    file.write("            ! Structural control indices\n")
    file.write("            IF (CntrPar%StC_Mode > 0) THEN\n")
    file.write("                DO Ind = 1, SIZE(CntrPar%StC_GroupIndex)\n")
    file.write("                    Call AddToList(avrIndices,CntrPar%StC_GroupIndex(Ind))\n")
    file.write("                END DO\n")
    file.write("            END IF\n")
    file.write("\n")
    file.write("            ! Format string\n")
    file.write("            avrFmt = '(A21,'//TRIM(Int2LStr(SIZE(avrIndices)))//'(TR12," + '"' + "'//'" + "AvrSWAP(" + '",I4,"' + ')"' + "))'\n")
    # file.write("            WRITE(UnDb3,'"+'(A,85("'+"'//Tab//'"+'AvrSWAP("'+',I2,")"'+"))')  'LocalVar%Time ', (i,i=1, 85)\n")
    file.write("\n")
    file.write("            CALL GetNewUnit(UnDb3, ErrVar)\n")
    file.write("            OPEN(unit=UnDb3, FILE=TRIM(RootName)//'.RO.dbg3')\n")
    file.write("            WRITE(UnDb3,'(/////)')\n")
    file.write("            WRITE(UnDb3,avrFmt)  'LocalVar%Time ', (avrIndices)\n")
    file.write("            WRITE(UnDb3,'(A21,'//TRIM(Int2LStr(SIZE(avrIndices)))//'(TR22," + '"(-)"' + "))')  '(s)'\n")
    file.write("        END IF\n")
    file.write("    END IF\n")
    file.write("\n")
    file.write("        ! Print simulation status, every 10 seconds\n")
    file.write("    IF (MODULO(LocalVar%Time, 10.0_DbKi) == 0) THEN\n")
    file.write("        WRITE(*, 100) LocalVar%GenSpeedF*RPS2RPM, LocalVar%BlPitch(1)*R2D, avrSWAP(15)/1000.0, LocalVar%WE_Vw\n")
    file.write("        100 FORMAT('Generator speed: ', f6.1, ' RPM, Pitch angle: ', f5.1, ' deg, Power: ', f7.1, ' kW, Est. wind Speed: ', f5.1, ' m/s')\n")
    file.write("    END IF\n")
    file.write("\n")
    file.write("    ! Process DebugOutData, LocalVarOutData\n")
    file.write("    ! Remove very small numbers that cause ******** outputs\n")
    file.write("    DO I = 1,SIZE(DebugOutData)\n")
    file.write("        IF (ABS(DebugOutData(I)) < 1E-99) THEN\n")
    file.write("            DebugOutData(I) = 0\n")
    file.write("        END IF\n")
    file.write("        IF (ABS(DebugOutData(I)) > 1E+99) THEN\n")
    file.write("            DebugOutData(I) = 1E+99\n")
    file.write("        END IF\n")
    file.write("    END DO\n")
    file.write("    \n")
    file.write("    DO I = 1,SIZE(LocalVarOutData)\n")
    file.write("        IF (ABS(LocalVarOutData(I)) < 1E-99) THEN\n")
    file.write("            LocalVarOutData(I) = 0\n")
    file.write("        END IF\n")
    file.write("        IF (ABS(LocalVarOutData(I)) > 1E+99) THEN\n")
    file.write("            LocalVarOutData(I) = 1E+99\n")
    file.write("        END IF\n")
    file.write("    END DO\n")
    file.write("    \n")
    file.write("    ! Write debug files\n")
    file.write(f'    FmtDat = "(F20.5,TR5,{n_lv_outputs}(ES20.5E2,TR5:))"   ! The format of the debugging data\n')
    file.write("    IF ( MOD(LocalVar%n_DT, CntrPar%n_DT_Out) == 0) THEN\n")
    file.write("        IF((CntrPar%LoggingLevel > 0) .AND. (LocalVar%iStatus .ge. 0)) THEN\n")
    file.write("            WRITE (UnDb, TRIM(FmtDat))  LocalVar%Time, DebugOutData\n")
    file.write("        END IF\n")
    file.write("\n")
    file.write("        IF((CntrPar%LoggingLevel > 1) .AND. (LocalVar%iStatus .ge. 0)) THEN\n")
    file.write("            WRITE (UnDb2, TRIM(FmtDat))  LocalVar%Time, LocalVarOutData\n")
    file.write("        END IF\n")
    file.write("\n")
    file.write("        IF((CntrPar%LoggingLevel > 2) .AND. (LocalVar%iStatus .ge. 0)) THEN\n")
    file.write("            WRITE (UnDb3, TRIM(FmtDat))    LocalVar%Time, avrSWAP(avrIndices)\n")
    file.write("        END IF\n")
    file.write("    END IF\n")
    file.write("\n")
    file.write("    ! Close all files when simulation finished\n")
    file.write("    IF (LocalVar%iStatus < 0) THEN\n")
    file.write("        CLOSE(UnDb)\n")
    file.write("        CLOSE(UnDb2)\n")
    file.write("        CLOSE(UnDb3)\n")
    file.write("    ENDIF\n")

    file.write("END SUBROUTINE Debug\n")
    file.write("\n")
    file.write("END MODULE ROSCO_IO\n")
    file.close()

def check_size(main_attribute, sub_attribute):
    if main_attribute[sub_attribute]['type'] == 'derived_type':
        atstr = sub_attribute
    else:
        size = int(main_attribute[sub_attribute]['size'])
        if size == 0:
            atstr = sub_attribute
        else:
            atstr = sub_attribute + '({})'.format(size)
    return atstr

def read_type(param):
    if param['type'] == 'integer':
        f90type = 'INTEGER(IntKi)'
        if param['allocatable']:
            f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'real':
        f90type = 'REAL(DbKi)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'complex':
        f90type = 'COMPLEX(DbKi)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'float':
        f90type = 'REAL(ReKi)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'character':
        f90type = 'CHARACTER'
        if param['length']:
            f90type += '({})'.format(param['length'])
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type = 'CHARACTER(:), ALLOCATABLE'
    elif param['type'] == 'logical':
        f90type = 'LOGICAL'
    elif param['type'] == 'c_integer':
        f90type = 'INTEGER(C_INT)'
    elif param['type'] == 'c_float':
        f90type = 'REAL(C_FLOAT)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'c_pointer':
        f90type = 'TYPE(C_PTR)'
    elif param['type'] == 'c_intptr_t':
        f90type = 'INTEGER(C_INTPTR_T)'
    elif param['type'] == 'c_funptr':
        f90type = 'TYPE(C_FUNPTR)'
    elif param['type'] == 'derived_type':
        f90type = 'TYPE({})'.format(param['id'])
    else:
        raise AttributeError('{} does not have a recognizable type'.format(param['type']))


    return f90type

def generate(yfile):
    '''
    Generates full registry and ROSCO I/O files (Fortran + C++)
    '''
    write_types(yfile)
    write_roscoio(yfile)
    generate_cpp(yfile)

# ============================================================
# C++ Code Generation
# ============================================================

def _extract_sections(yfile, typename):
    """
    Parse raw YAML text to map parameter names to their section comment label.
    Section comments are lines like '    # Filters' (4-space indent).
    Returns dict: {param_name: section_label}
    """
    result = {}
    current = None
    in_type = False
    with open(yfile) as f:
        for raw in f:
            stripped = raw.strip()
            if not in_type:
                if stripped == f'{typename}:':
                    in_type = True
                continue
            # Exit when we hit a new top-level YAML key (no leading whitespace)
            if raw and raw[0] not in ' \t\n\r' and ':' in stripped and not stripped.startswith('#'):
                break
            # Section comment: exactly 4-space indent + '#'
            if raw.startswith('    #') and stripped.startswith('#'):
                current = stripped.lstrip('#').strip()
            # Parameter name: 4-space indent, ends with ':', no spaces, not a comment
            elif (raw.startswith('    ') and not raw.startswith('      ')
                  and not stripped.startswith('#')
                  and stripped.endswith(':') and ' ' not in stripped):
                result[stripped.rstrip(':')] = current
    return result


def _cpp_type(param):
    """
    Return (cpp_type_str, is_2d_alloc) for a YAML parameter entry.
    Returns (None, False) for types to skip (derived_type, c_pointer, etc.).
    """
    ptype  = param.get('type', '')
    alloc  = param.get('allocatable', False)
    dim    = param.get('dimension', None)
    is_2d  = bool(alloc and dim and ',' in str(dim))

    if alloc:
        if ptype in ('real', 'float', 'complex'):
            return 'ParamArray', is_2d
        elif ptype in ('integer', 'c_integer', 'logical'):
            return 'std::vector<int>', is_2d
        elif ptype == 'c_float':
            return 'std::vector<float>', is_2d
        elif ptype == 'character':
            return 'std::vector<std::string>', is_2d
        else:
            return None, False
    else:
        if ptype in ('integer', 'c_integer'):
            return 'int', False
        elif ptype in ('real', 'complex', 'float'):
            return 'double', False
        elif ptype == 'c_float':
            return 'float', False
        elif ptype == 'logical':
            return 'int', False
        elif ptype == 'character':
            return 'std::string', False
        elif ptype in ('c_pointer', 'c_funptr', 'c_intptr_t', 'derived_type'):
            return None, False
        else:
            return None, False


def _default_val(cpp_type, param):
    """Return initializer string for a plain (non-vector) C++ field."""
    eq = param.get('equals')
    if eq is not None:
        return str(eq)
    if cpp_type == 'double':
        return '0.0'
    if cpp_type == 'float':
        return '0.0f'
    return '0'


def generate_cpp(yfile):
    """
    Generate C++ files from rosco_types.yaml:
      - src/include/rosco_types.hpp   : ControlParameters struct (std::vector, std::string)
      - src/rosco_types_io.cpp        : TOML loader + populate_view()
      - ../../Examples/DISCON_template.toml : annotated TOML input template
    """
    _write_cpp_header(yfile)
    _write_cpp_io(yfile)
    _write_toml_template(yfile)


def _write_cpp_header(yfile):
    """Generate rosco/controller/src/include/rosco_types.hpp"""
    reg = load_yaml(yfile)
    reg.pop('default_types', None)

    src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src')
    out_path = os.path.join(src_dir, 'include', 'rosco_types.hpp')

    sections = _extract_sections(yfile, 'ControlParameters')
    params   = reg['ControlParameters']

    with open(out_path, 'w') as f:
        f.write('// AUTO-GENERATED from rosco_types.yaml\n')
        f.write('// Do not edit manually — run write_registry.py to regenerate.\n')
        f.write('#pragma once\n')
        f.write('#include <vector>\n')
        f.write('#include <string>\n')
        f.write('#include "rosco_array.hpp"\n')
        f.write('#include "vit_types.h"\n')
        f.write('\n')
        f.write('struct ControlParameters {\n')

        prev_section = None
        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue

            section = sections.get(name)
            if section and section != prev_section:
                f.write(f'\n    // --- {section} ---\n')
                prev_section = section

            desc = (param.get('description') or '').strip()
            if desc:
                desc = desc[:120] + '...' if len(desc) > 120 else desc
                f.write(f'    // {desc}\n')

            if 'vector' in cpp_type or cpp_type in ('std::string', 'ParamArray'):
                f.write(f'    {cpp_type} {name};\n')
                if is_2d:
                    f.write(f'    int {name}_rows = 0;\n')
                    f.write(f'    int {name}_cols = 0;\n')
            else:
                default = _default_val(cpp_type, param)
                f.write(f'    {cpp_type:<8s} {name} = {default};\n')

        f.write('\n')
        f.write('    // Load all parameters from a TOML file (replaces DISCON.IN two-pass parser)\n')
        f.write('    bool load_from_toml(const std::string& path, errorvariables_t* err);\n')
        f.write('\n')
        f.write('    // Populate legacy controlparameters_view_t for translated functions\n')
        f.write('    void populate_view(controlparameters_view_t* v) const;\n')
        f.write('\n')
        f.write('    // Copy all fields from a populated controlparameters_view_t (DISCON.IN path bridge)\n')
        f.write('    void sync_from_view(const controlparameters_view_t& v);\n')
        f.write('};\n')


def _write_cpp_io(yfile):
    """Generate rosco/controller/src/rosco_types_io.cpp"""
    reg = load_yaml(yfile)
    reg.pop('default_types', None)
    params = reg['ControlParameters']

    src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src')
    out_path = os.path.join(src_dir, 'rosco_types_io.cpp')

    with open(out_path, 'w') as f:
        f.write('// AUTO-GENERATED from rosco_types.yaml\n')
        f.write('// Do not edit manually — run write_registry.py to regenerate.\n')
        f.write('#include "include/rosco_types.hpp"\n')
        f.write('#include <toml++/toml.hpp>\n')
        f.write('#include <cstring>\n')
        f.write('#include <cstdio>\n')
        f.write('\n')
        f.write('// Space-pad a C char array in Fortran style\n')
        f.write('static void set_fstr(char* dest, int maxLen, const std::string& src) {\n')
        f.write('    std::memset(dest, \' \', maxLen);\n')
        f.write('    size_t n = src.size() < (size_t)maxLen ? src.size() : (size_t)maxLen;\n')
        f.write('    std::memcpy(dest, src.c_str(), n);\n')
        f.write('}\n')
        f.write('\n')

        # ---- load_from_toml ----
        f.write('bool ControlParameters::load_from_toml(const std::string& path, errorvariables_t* err) {\n')
        f.write('    toml::table tbl;\n')
        f.write('    try {\n')
        f.write('        tbl = toml::parse_file(path);\n')
        f.write('    } catch (const toml::parse_error& e) {\n')
        f.write('        err->aviFAIL = -1;\n')
        f.write('        std::snprintf(err->ErrMsg, 1024, "TOML parse error in %s: %s",\n')
        f.write('                      path.c_str(), e.description().data());\n')
        f.write('        return false;\n')
        f.write('    }\n')
        f.write('\n')

        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype = param.get('type', '')
            alloc = param.get('allocatable', False)

            if alloc:
                if cpp_type == 'ParamArray':
                    f.write(f'    if (auto* arr = tbl["{name}"].as_array()) {{\n')
                    f.write(f'        {name}.clear();\n')
                    if is_2d:
                        # 2D: read row-by-row, then store in column-major order
                        # (matching Fortran/existing translated-function convention)
                        f.write(f'        std::vector<std::vector<double>> _tmp_{name};\n')
                        f.write(f'        for (auto& _row : *arr) {{\n')
                        f.write(f'            if (auto* _ra = _row.as_array()) {{\n')
                        f.write(f'                std::vector<double> _rv;\n')
                        f.write(f'                for (auto& el : *_ra) _rv.push_back(el.value_or(0.0));\n')
                        f.write(f'                _tmp_{name}.push_back(std::move(_rv));\n')
                        f.write(f'            }}\n')
                        f.write(f'        }}\n')
                        f.write(f'        {name}_rows = (int)_tmp_{name}.size();\n')
                        f.write(f'        {name}_cols = {name}_rows > 0 ? (int)_tmp_{name}[0].size() : 0;\n')
                        f.write(f'        {name}.resize((size_t){name}_rows * {name}_cols);\n')
                        f.write(f'        for (int _c = 0; _c < {name}_cols; ++_c)\n')
                        f.write(f'            for (int _r = 0; _r < {name}_rows; ++_r)\n')
                        f.write(f'                {name}[_c * {name}_rows + _r] = _tmp_{name}[_r][_c];\n')
                    else:
                        f.write(f'        for (auto& el : *arr) {name}.push_back(el.value_or(0.0));\n')
                    f.write(f'    }}\n')
                elif 'int' in cpp_type:
                    f.write(f'    if (auto* arr = tbl["{name}"].as_array()) {{\n')
                    f.write(f'        {name}.clear();\n')
                    f.write(f'        for (auto& el : *arr) {name}.push_back((int)el.value_or((int64_t)0));\n')
                    f.write(f'    }}\n')
            elif ptype == 'character':
                length = param.get('length', 1024)
                f.write(f'    {name} = tbl["{name}"].value_or(std::string{{}});\n')
            elif cpp_type == 'double':
                f.write(f'    {name} = tbl["{name}"].value_or(0.0);\n')
            elif cpp_type == 'int':
                f.write(f'    {name} = (int)tbl["{name}"].value_or((int64_t)0);\n')
            elif cpp_type == 'float':
                f.write(f'    {name} = (float)tbl["{name}"].value_or(0.0);\n')

        f.write('\n    return err->aviFAIL >= 0;\n')
        f.write('}\n')
        f.write('\n')

        # ---- populate_view ----
        f.write('void ControlParameters::populate_view(controlparameters_view_t* v) const {\n')

        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype = param.get('type', '')
            alloc = param.get('allocatable', False)

            if alloc:
                if is_2d:
                    # view has: double* name; int32_t n_name_rows; int32_t n_name_cols;
                    f.write(f'    v->{name} = {name}.empty() ? nullptr : const_cast<double*>({name}.data());\n')
                    f.write(f'    v->n_{name}_rows = (int32_t){name}_rows;\n')
                    f.write(f'    v->n_{name}_cols = (int32_t){name}_cols;\n')
                elif cpp_type == 'ParamArray':
                    f.write(f'    v->{name} = {name}.empty() ? nullptr : const_cast<double*>({name}.data());\n')
                    f.write(f'    v->n_{name} = (int32_t){name}.size();\n')
                elif 'int' in cpp_type:
                    f.write(f'    v->{name} = {name}.empty() ? nullptr : const_cast<int*>({name}.data());\n')
                    f.write(f'    v->n_{name} = (int32_t){name}.size();\n')
            elif ptype == 'character':
                length = param.get('length', 1024)
                f.write(f'    set_fstr(v->{name}, {length}, {name});\n')
            else:
                f.write(f'    v->{name} = {name};\n')

        f.write('}\n')

        # ---- sync_from_view ----
        f.write('\n')
        f.write('void ControlParameters::sync_from_view(const controlparameters_view_t& v) {\n')

        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype = param.get('type', '')
            alloc = param.get('allocatable', False)

            if alloc:
                if is_2d:
                    f.write(f'    if (v.{name} && v.n_{name}_rows > 0 && v.n_{name}_cols > 0) {{\n')
                    f.write(f'        {name}.storage.assign(v.{name}, v.{name} + (size_t)v.n_{name}_rows * v.n_{name}_cols);\n')
                    f.write(f'        {name}_rows = v.n_{name}_rows;\n')
                    f.write(f'        {name}_cols = v.n_{name}_cols;\n')
                    f.write(f'    }}\n')
                elif cpp_type == 'ParamArray':
                    f.write(f'    if (v.{name} && v.n_{name} > 0)\n')
                    f.write(f'        {name}.storage.assign(v.{name}, v.{name} + v.n_{name});\n')
                elif 'int' in cpp_type:
                    f.write(f'    if (v.{name} && v.n_{name} > 0)\n')
                    f.write(f'        {name}.assign(v.{name}, v.{name} + v.n_{name});\n')
            elif ptype == 'character':
                length = param.get('length', 1024)
                f.write(f'    {{\n')
                f.write(f'        int _len = {length};\n')
                f.write(f'        while (_len > 0 && v.{name}[_len-1] == \' \') _len--;\n')
                f.write(f'        {name} = std::string(v.{name}, _len);\n')
                f.write(f'    }}\n')
            else:
                f.write(f'    {name} = v.{name};\n')

        f.write('}\n')


def _write_toml_template(yfile):
    """Generate Examples/DISCON_template.toml"""
    reg = load_yaml(yfile)
    reg.pop('default_types', None)
    params = reg['ControlParameters']

    sections = _extract_sections(yfile, 'ControlParameters')

    # DISCON_template.toml goes next to existing DISCON.IN examples
    examples_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
        'Examples')
    out_path = os.path.join(examples_dir, 'DISCON_template.toml')

    with open(out_path, 'w') as f:
        f.write('# ROSCO Controller Configuration — TOML format\n')
        f.write('# AUTO-GENERATED template from rosco_types.yaml\n')
        f.write('# Edit this file to configure your controller.\n')
        f.write('# Array parameters: use TOML native array syntax, e.g. PC_GS_angles = [0.1, 0.2, 0.3]\n')
        f.write('# Count scalars (PC_GS_n, VS_n, etc.) are derived from array length — omit them.\n')
        f.write('\n')

        prev_section = None
        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype  = param.get('type', '')
            alloc  = param.get('allocatable', False)

            section = sections.get(name)
            if section and section != prev_section:
                f.write(f'\n# ===== {section} =====\n')
                prev_section = section

            desc = (param.get('description') or '').strip()
            if desc:
                f.write(f'# {desc}\n')

            eq = param.get('equals')

            if alloc:
                if is_2d:
                    f.write(f'# {name} = [[...], [...]]  # 2D array (rows x cols)\n')
                else:
                    f.write(f'# {name} = []  # array\n')
            elif ptype == 'character':
                val = f'"{eq}"' if eq else '""'
                f.write(f'{name} = {val}\n')
            elif cpp_type == 'double':
                val = eq if eq is not None else 0.0
                f.write(f'{name} = {val}\n')
            elif cpp_type == 'int':
                val = eq if eq is not None else 0
                f.write(f'{name} = {val}\n')
            else:
                f.write(f'# {name} = ...\n')


if __name__ == '__main__':
    fname = os.path.join(os.path.dirname(os.path.abspath(__file__)),'rosco_types.yaml')
    generate(fname)

