import yaml
import rosco.toolbox
import os
from rosco.toolbox.ofTools.util.FileTools import load_yaml

def write_types(yfile):
    '''
    Writes ROSCO_types.f90
    -- All additions to the types should be added to rosco_types.yaml!

    Parameters:
    -----------
    yfile: string
            path to rosco_types.yaml
    '''
    reg = load_yaml(yfile)
    reg.pop('default_types')
    registry_fname = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),'src','ROSCO_Types.f90')
    file = open(registry_fname, 'w')
    # Header
    file.write('! ROSCO Registry\n')
    file.write('! This file is automatically generated by write_registry.py using ROSCO v{}\n'.format(rosco.toolbox.__version__))
    file.write('! For any modification to the registry, please edit the rosco_types.yaml accordingly\n \n')
    file.write('MODULE ROSCO_Types\n') 
    file.write('USE, INTRINSIC :: ISO_C_Binding\n')
    file.write('USE Constants\n')
    file.write('IMPLICIT NONE\n')
    file.write('\n')
    file.write(f"Character(*), PARAMETER     :: rosco_version = '{rosco.toolbox.__version__}'             ! ROSCO version\n")
    file.write('\n')
    # Loop Types
    for toptype in reg.keys():
        file.write('TYPE, PUBLIC :: {}\n'.format(toptype))
        for attype in reg[toptype].keys():
            f90type = read_type(reg[toptype][attype])
            atstr  =  check_size(reg[toptype], attype)
            if reg[toptype][attype]['equals'] is not None:
                atstr += ' = ' + str(reg[toptype][attype]['equals'])
            file.write('    {:<25s}     :: {:<25s}   ! {}\n'.format(f90type, atstr, reg[toptype][attype]['description']))
        file.write('END TYPE {}\n'.format(toptype))
        file.write('\n')
    file.write('END MODULE ROSCO_Types\n')
    file.close()

def check_size(main_attribute, sub_attribute):
    if main_attribute[sub_attribute]['type'] == 'derived_type':
        atstr = sub_attribute
    else:
        size = int(main_attribute[sub_attribute]['size'])
        if size == 0:
            atstr = sub_attribute
        else:
            atstr = sub_attribute + '({})'.format(size)
    return atstr

def read_type(param):
    if param['type'] == 'integer':
        f90type = 'INTEGER(IntKi)'
        if param['allocatable']:
            f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'real':
        f90type = 'REAL(DbKi)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'complex':
        f90type = 'COMPLEX(DbKi)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'float':
        f90type = 'REAL(ReKi)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'character':
        f90type = 'CHARACTER'
        if param['length']:
            f90type += '({})'.format(param['length'])
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type = 'CHARACTER(:), ALLOCATABLE'
    elif param['type'] == 'logical':
        f90type = 'LOGICAL'
    elif param['type'] == 'c_integer':
        f90type = 'INTEGER(C_INT)'
    elif param['type'] == 'c_float':
        f90type = 'REAL(C_FLOAT)'
        if param['allocatable']:
            if param['dimension']:
                f90type += ', DIMENSION{}, ALLOCATABLE'.format(param['dimension'])
            else:
                f90type += ', DIMENSION(:), ALLOCATABLE'
        elif param['dimension']:
            f90type += ', DIMENSION{}'.format(param['dimension'])
    elif param['type'] == 'c_pointer':
        f90type = 'TYPE(C_PTR)'
    elif param['type'] == 'c_intptr_t':
        f90type = 'INTEGER(C_INTPTR_T)'
    elif param['type'] == 'c_funptr':
        f90type = 'TYPE(C_FUNPTR)'
    elif param['type'] == 'derived_type':
        f90type = 'TYPE({})'.format(param['id'])
    else:
        raise AttributeError('{} does not have a recognizable type'.format(param['type']))


    return f90type

def generate(yfile):
    '''
    Generates full registry and ROSCO I/O files (Fortran types + C++)
    '''
    write_types(yfile)
    generate_cpp(yfile)

# ============================================================
# C++ Code Generation
# ============================================================

def _extract_sections(yfile, typename):
    """
    Parse raw YAML text to map parameter names to their section comment label.
    Section comments are lines like '    # Filters' (4-space indent).
    Returns dict: {param_name: section_label}
    """
    result = {}
    current = None
    in_type = False
    with open(yfile) as f:
        for raw in f:
            stripped = raw.strip()
            if not in_type:
                if stripped == f'{typename}:':
                    in_type = True
                continue
            # Exit when we hit a new top-level YAML key (no leading whitespace)
            if raw and raw[0] not in ' \t\n\r' and ':' in stripped and not stripped.startswith('#'):
                break
            # Section comment: exactly 4-space indent + '#'
            if raw.startswith('    #') and stripped.startswith('#'):
                current = stripped.lstrip('#').strip()
            # Parameter name: 4-space indent, ends with ':', no spaces, not a comment
            elif (raw.startswith('    ') and not raw.startswith('      ')
                  and not stripped.startswith('#')
                  and stripped.endswith(':') and ' ' not in stripped):
                result[stripped.rstrip(':')] = current
    return result


def _cpp_type(param):
    """
    Return (cpp_type_str, is_2d_alloc) for a YAML parameter entry.
    Returns (None, False) for types to skip (derived_type, c_pointer, etc.).
    """
    ptype  = param.get('type', '')
    alloc  = param.get('allocatable', False)
    dim    = param.get('dimension', None)
    is_2d  = bool(alloc and dim and ',' in str(dim))

    if alloc:
        if ptype in ('real', 'float', 'complex'):
            return 'ParamArray', is_2d
        elif ptype in ('integer', 'c_integer', 'logical'):
            return 'std::vector<int>', is_2d
        elif ptype == 'c_float':
            return 'std::vector<float>', is_2d
        elif ptype == 'character':
            return 'std::vector<std::string>', is_2d
        else:
            return None, False
    else:
        if ptype in ('integer', 'c_integer'):
            return 'int', False
        elif ptype in ('real', 'complex', 'float'):
            return 'double', False
        elif ptype == 'c_float':
            return 'float', False
        elif ptype == 'logical':
            return 'int', False
        elif ptype == 'character':
            return 'std::string', False
        elif ptype in ('c_pointer', 'c_funptr', 'c_intptr_t', 'derived_type'):
            return None, False
        else:
            return None, False


def _default_val(cpp_type, param):
    """Return initializer string for a plain (non-vector) C++ field."""
    eq = param.get('equals')
    if eq is not None:
        return str(eq)
    if cpp_type == 'double':
        return '0.0'
    if cpp_type == 'float':
        return '0.0f'
    return '0'


def generate_cpp(yfile):
    """
    Generate C++ files from rosco_types.yaml:
      - src/include/rosco_types.hpp   : ControlParameters struct (std::vector, std::string)
      - src/rosco_types_io.cpp        : TOML loader + populate_view()
      - src/IO/debug.cpp              : Debug output (dbg, dbg2, dbg3)
      - ../../Examples/DISCON_template.toml : annotated TOML input template
    """
    _write_cpp_header(yfile)
    _write_cpp_io(yfile)
    _write_cpp_debug(yfile)
    _write_toml_template(yfile)


def _write_cpp_header(yfile):
    """Generate rosco/controller/src/include/rosco_types.hpp"""
    reg = load_yaml(yfile)
    reg.pop('default_types', None)

    src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src')
    out_path = os.path.join(src_dir, 'include', 'rosco_types.hpp')

    sections = _extract_sections(yfile, 'ControlParameters')
    params   = reg['ControlParameters']

    with open(out_path, 'w') as f:
        f.write('// AUTO-GENERATED from rosco_types.yaml\n')
        f.write('// Do not edit manually — run write_registry.py to regenerate.\n')
        f.write('#pragma once\n')
        f.write('#include <vector>\n')
        f.write('#include <string>\n')
        f.write('#include "rosco_array.hpp"\n')
        f.write('#include "vit_types.h"\n')
        f.write('\n')
        f.write('struct ControlParameters {\n')

        prev_section = None
        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue

            section = sections.get(name)
            if section and section != prev_section:
                f.write(f'\n    // --- {section} ---\n')
                prev_section = section

            desc = (param.get('description') or '').strip()
            if desc:
                desc = desc[:120] + '...' if len(desc) > 120 else desc
                f.write(f'    // {desc}\n')

            if 'vector' in cpp_type or cpp_type in ('std::string', 'ParamArray'):
                f.write(f'    {cpp_type} {name};\n')
                if is_2d:
                    f.write(f'    int {name}_rows = 0;\n')
                    f.write(f'    int {name}_cols = 0;\n')
            else:
                default = _default_val(cpp_type, param)
                f.write(f'    {cpp_type:<8s} {name} = {default};\n')

        f.write('\n')
        f.write('    // Load all parameters from a TOML file (replaces DISCON.IN two-pass parser)\n')
        f.write('    bool load_from_toml(const std::string& path, errorvariables_t* err);\n')
        f.write('\n')
        f.write('    // Populate legacy controlparameters_view_t for translated functions\n')
        f.write('    void populate_view(controlparameters_view_t* v) const;\n')
        f.write('\n')
        f.write('    // Copy all fields from a populated controlparameters_view_t (DISCON.IN path bridge)\n')
        f.write('    void sync_from_view(const controlparameters_view_t& v);\n')
        f.write('};\n')


def _write_cpp_io(yfile):
    """Generate rosco/controller/src/rosco_types_io.cpp"""
    reg = load_yaml(yfile)
    reg.pop('default_types', None)
    params = reg['ControlParameters']

    src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src')
    out_path = os.path.join(src_dir, 'rosco_types_io.cpp')

    with open(out_path, 'w') as f:
        f.write('// AUTO-GENERATED from rosco_types.yaml\n')
        f.write('// Do not edit manually — run write_registry.py to regenerate.\n')
        f.write('#include "include/rosco_types.hpp"\n')
        f.write('#include <toml++/toml.hpp>\n')
        f.write('#include <cstring>\n')
        f.write('#include <cstdio>\n')
        f.write('\n')
        f.write('// Space-pad a C char array in Fortran style\n')
        f.write('static void set_fstr(char* dest, int maxLen, const std::string& src) {\n')
        f.write('    std::memset(dest, \' \', maxLen);\n')
        f.write('    size_t n = src.size() < (size_t)maxLen ? src.size() : (size_t)maxLen;\n')
        f.write('    std::memcpy(dest, src.c_str(), n);\n')
        f.write('}\n')
        f.write('\n')

        # ---- load_from_toml ----
        f.write('bool ControlParameters::load_from_toml(const std::string& path, errorvariables_t* err) {\n')
        f.write('    toml::table tbl;\n')
        f.write('    try {\n')
        f.write('        tbl = toml::parse_file(path);\n')
        f.write('    } catch (const toml::parse_error& e) {\n')
        f.write('        err->aviFAIL = -1;\n')
        f.write('        std::snprintf(err->ErrMsg, 1024, "TOML parse error in %s: %s",\n')
        f.write('                      path.c_str(), e.description().data());\n')
        f.write('        return false;\n')
        f.write('    }\n')
        f.write('\n')

        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype = param.get('type', '')
            alloc = param.get('allocatable', False)

            if alloc:
                if cpp_type == 'ParamArray':
                    f.write(f'    if (auto* arr = tbl["{name}"].as_array()) {{\n')
                    f.write(f'        {name}.clear();\n')
                    if is_2d:
                        # 2D: read row-by-row, then store in column-major order
                        # (matching Fortran/existing translated-function convention)
                        f.write(f'        std::vector<std::vector<double>> _tmp_{name};\n')
                        f.write(f'        for (auto& _row : *arr) {{\n')
                        f.write(f'            if (auto* _ra = _row.as_array()) {{\n')
                        f.write(f'                std::vector<double> _rv;\n')
                        f.write(f'                for (auto& el : *_ra) _rv.push_back(el.value_or(0.0));\n')
                        f.write(f'                _tmp_{name}.push_back(std::move(_rv));\n')
                        f.write(f'            }}\n')
                        f.write(f'        }}\n')
                        f.write(f'        {name}_rows = (int)_tmp_{name}.size();\n')
                        f.write(f'        {name}_cols = {name}_rows > 0 ? (int)_tmp_{name}[0].size() : 0;\n')
                        f.write(f'        {name}.resize((size_t){name}_rows * {name}_cols);\n')
                        f.write(f'        for (int _c = 0; _c < {name}_cols; ++_c)\n')
                        f.write(f'            for (int _r = 0; _r < {name}_rows; ++_r)\n')
                        f.write(f'                {name}[_c * {name}_rows + _r] = _tmp_{name}[_r][_c];\n')
                    else:
                        f.write(f'        for (auto& el : *arr) {name}.push_back(el.value_or(0.0));\n')
                    f.write(f'    }}\n')
                elif 'int' in cpp_type:
                    f.write(f'    if (auto* arr = tbl["{name}"].as_array()) {{\n')
                    f.write(f'        {name}.clear();\n')
                    f.write(f'        for (auto& el : *arr) {name}.push_back((int)el.value_or((int64_t)0));\n')
                    f.write(f'    }}\n')
            elif ptype == 'character':
                length = param.get('length', 1024)
                f.write(f'    {name} = tbl["{name}"].value_or(std::string{{}});\n')
            elif cpp_type == 'double':
                f.write(f'    {name} = tbl["{name}"].value_or(0.0);\n')
            elif cpp_type == 'int':
                f.write(f'    {name} = (int)tbl["{name}"].value_or((int64_t)0);\n')
            elif cpp_type == 'float':
                f.write(f'    {name} = (float)tbl["{name}"].value_or(0.0);\n')

        f.write('\n    return err->aviFAIL >= 0;\n')
        f.write('}\n')
        f.write('\n')

        # ---- populate_view ----
        f.write('void ControlParameters::populate_view(controlparameters_view_t* v) const {\n')

        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype = param.get('type', '')
            alloc = param.get('allocatable', False)

            if alloc:
                if is_2d:
                    # view has: double* name; int32_t n_name_rows; int32_t n_name_cols;
                    f.write(f'    v->{name} = {name}.empty() ? nullptr : const_cast<double*>({name}.data());\n')
                    f.write(f'    v->n_{name}_rows = (int32_t){name}_rows;\n')
                    f.write(f'    v->n_{name}_cols = (int32_t){name}_cols;\n')
                elif cpp_type == 'ParamArray':
                    f.write(f'    v->{name} = {name}.empty() ? nullptr : const_cast<double*>({name}.data());\n')
                    f.write(f'    v->n_{name} = (int32_t){name}.size();\n')
                elif 'int' in cpp_type:
                    f.write(f'    v->{name} = {name}.empty() ? nullptr : const_cast<int*>({name}.data());\n')
                    f.write(f'    v->n_{name} = (int32_t){name}.size();\n')
            elif ptype == 'character':
                length = param.get('length', 1024)
                f.write(f'    set_fstr(v->{name}, {length}, {name});\n')
            else:
                f.write(f'    v->{name} = {name};\n')

        f.write('}\n')

        # ---- sync_from_view ----
        f.write('\n')
        f.write('void ControlParameters::sync_from_view(const controlparameters_view_t& v) {\n')

        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype = param.get('type', '')
            alloc = param.get('allocatable', False)

            if alloc:
                if is_2d:
                    f.write(f'    if (v.{name} && v.n_{name}_rows > 0 && v.n_{name}_cols > 0) {{\n')
                    f.write(f'        {name}.storage.assign(v.{name}, v.{name} + (size_t)v.n_{name}_rows * v.n_{name}_cols);\n')
                    f.write(f'        {name}_rows = v.n_{name}_rows;\n')
                    f.write(f'        {name}_cols = v.n_{name}_cols;\n')
                    f.write(f'    }}\n')
                elif cpp_type == 'ParamArray':
                    f.write(f'    if (v.{name} && v.n_{name} > 0)\n')
                    f.write(f'        {name}.storage.assign(v.{name}, v.{name} + v.n_{name});\n')
                elif 'int' in cpp_type:
                    f.write(f'    if (v.{name} && v.n_{name} > 0)\n')
                    f.write(f'        {name}.assign(v.{name}, v.{name} + v.n_{name});\n')
            elif ptype == 'character':
                length = param.get('length', 1024)
                f.write(f'    {{\n')
                f.write(f'        int _len = {length};\n')
                f.write(f'        while (_len > 0 && v.{name}[_len-1] == \' \') _len--;\n')
                f.write(f'        {name} = std::string(v.{name}, _len);\n')
                f.write(f'    }}\n')
            else:
                f.write(f'    {name} = v.{name};\n')

        f.write('}\n')


def _extract_unit(desc):
    """Extract unit string from description like 'Some text [rad/s]' → '[rad/s]'."""
    if not desc or '[' not in desc:
        return '[N/A]'
    unit = desc[desc.find('['):desc.find(']') + 1]
    return unit if unit else '[N/A]'


def _cpp_access(name, param):
    """Return (access_expr, needs_cast) for a LocalVariables field in C++."""
    ptype = param.get('type', '')
    size = param.get('size', 0)
    alloc = param.get('allocatable', False)

    if ptype in ('integer', 'c_integer', 'logical'):
        if size > 0 or alloc:
            return f'(double)LocalVar.{name}[0]', False
        return f'(double)LocalVar.{name}', False
    elif ptype in ('real', 'float', 'complex'):
        if size > 0 or alloc:
            return f'LocalVar.{name}[0]', False
        return f'LocalVar.{name}', False
    elif ptype == 'character':
        if alloc:
            return f'(double)LocalVar.{name}.size()', False
        return None, False
    return None, False


def _write_cpp_debug(yfile):
    """Generate rosco/controller/src/IO/debug.cpp from registry."""
    reg = load_yaml(yfile)
    reg.pop('default_types', None)
    local_vars = reg['LocalVariables']

    src_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src')
    out_path = os.path.join(src_dir, 'IO', 'debug.cpp')

    # Collect .dbg fields (flagged with dbg: true)
    dbg_fields = []  # (field_name, dbg_name, unit, access_expr)
    for name, param in local_vars.items():
        if param.get('dbg', False):
            dbg_name = param.get('dbg_name', name)
            unit = _extract_unit(param.get('description', ''))
            access, _ = _cpp_access(name, param)
            if access is None:
                continue
            dbg_fields.append((name, dbg_name, unit, access))

    # Collect .dbg2 fields (all scalar numeric LocalVariables, excluding cpp: false)
    lv_fields = []  # (field_name, access_expr)
    for name, param in local_vars.items():
        if param.get('cpp', True) is False:
            continue
        ptype = param.get('type', '')
        if ptype in ('integer', 'real', 'complex', 'logical', 'character'):
            access, _ = _cpp_access(name, param)
            if access is not None:
                lv_fields.append((name, access))

    n_dbg = len(dbg_fields)
    n_lv = len(lv_fields)

    with open(out_path, 'w') as f:
        f.write('// AUTO-GENERATED from rosco_types.yaml — do not edit manually.\n')
        f.write('// Regenerate with: python write_registry.py\n')
        f.write('#include "../include/vit_types.h"\n')
        f.write('#include "../include/rosco_types.hpp"\n')
        f.write('#include "../include/rosco_constants.h"\n')
        f.write('#include "debug_writer.hpp"\n')
        f.write('#include <fstream>\n')
        f.write('#include <cmath>\n')
        f.write('#include <string>\n')
        f.write('#include <cstring>\n')
        f.write('#include <cstdio>\n')
        f.write('#include <ctime>\n')
        f.write('#include <vector>\n')
        f.write('#include <memory>\n')
        f.write('\n')
        f.write('static const char* ROSCO_VERSION = "2.10.1";\n')
        f.write('\n')
        f.write('namespace {\n')
        f.write('\n')
        f.write('double clamp_debug(double val) {\n')
        f.write('    if (std::abs(val) < 1E-99) return 0.0;\n')
        f.write('    if (std::abs(val) > 1E+99) return 1E+99;\n')
        f.write('    return val;\n')
        f.write('}\n')
        f.write('\n')
        f.write('} // anonymous namespace\n')
        f.write('\n')
        f.write('// Writers for .dbg and .dbg2 (text or HDF5 based on OutputFormat)\n')
        f.write('static std::unique_ptr<DebugWriter> dbg_writer;\n')
        f.write('static std::unique_ptr<DebugWriter> dbg2_writer;\n')
        f.write('// .dbg3 (avrSWAP) remains text-only for now (Phase 3 adds HDF5)\n')
        f.write('static std::ofstream dbg3_file;\n')
        f.write('static std::vector<int32_t> avr_indices;\n')
        f.write('\n')
        f.write('void Debug(LocalVariables& LocalVar, const ControlParameters& CntrPar,\n')
        f.write('           float* avrSWAP) {\n')
        f.write('\n')
        f.write('    const std::string& root = LocalVar.RootName;\n')
        f.write('\n')

        # --- .dbg data array ---
        f.write(f'    // --- Debug output data ({n_dbg} fields, from dbg: true in registry) ---\n')
        f.write(f'    const int nDebugOuts = {n_dbg};\n')
        f.write(f'    double DebugOutData[nDebugOuts] = {{\n')
        for i, (name, dbg_name, unit, access) in enumerate(dbg_fields):
            comma = ',' if i < n_dbg - 1 else ''
            f.write(f'        {access}{comma}\n')
        f.write('    };\n')

        # --- .dbg column names ---
        f.write(f'    const char* DebugOutStrings[nDebugOuts] = {{\n')
        for i, (name, dbg_name, unit, access) in enumerate(dbg_fields):
            comma = ',' if i < n_dbg - 1 else ''
            f.write(f'        "{dbg_name}"{comma}\n')
        f.write('    };\n')

        # --- .dbg units ---
        f.write(f'    const char* DebugOutUnits[nDebugOuts] = {{\n')
        for i, (name, dbg_name, unit, access) in enumerate(dbg_fields):
            comma = ',' if i < n_dbg - 1 else ''
            f.write(f'        "{unit}"{comma}\n')
        f.write('    };\n')
        f.write('\n')

        # --- .dbg2 data (guarded by LoggingLevel > 1) ---
        f.write(f'    // --- LocalVar output data ({n_lv} fields, only needed for .dbg2) ---\n')
        f.write(f'    const int nLocalVars = {n_lv};\n')
        f.write(f'    double LocalVarOutData[nLocalVars] = {{}};\n')
        f.write(f'    if (CntrPar.LoggingLevel > 1) {{\n')
        f.write(f'    double LocalVarOutData_init[nLocalVars] = {{\n')
        for i, (name, access) in enumerate(lv_fields):
            comma = ',' if i < n_lv - 1 else ''
            f.write(f'        {access}{comma}\n')
        f.write('    };\n')
        f.write('    std::memcpy(LocalVarOutData, LocalVarOutData_init, sizeof(LocalVarOutData));\n')
        f.write('    } // end LoggingLevel > 1 guard\n')

        # --- .dbg2 column names and units (needed for writer open) ---
        f.write(f'    const char* LocalVarOutStrings[nLocalVars] = {{\n')
        for i, (name, access) in enumerate(lv_fields):
            comma = ',' if i < n_lv - 1 else ''
            f.write(f'        "{name}"{comma}\n')
        f.write('    };\n')
        # .dbg2 has no units in the original format — use empty strings
        f.write(f'    const char* LocalVarOutUnits[nLocalVars];\n')
        f.write(f'    for (int i = 0; i < nLocalVars; i++) LocalVarOutUnits[i] = "";\n')
        f.write('\n')

        # --- File initialization using DebugWriter ---
        f.write('    // --- Initialize debug writers on first call ---\n')
        f.write('    if (LocalVar.iStatus == 0 || LocalVar.iStatus == -9) {\n')
        f.write('        if (LocalVar.iStatus == -9) {\n')
        f.write('            if (dbg_writer) { dbg_writer->close(); dbg_writer.reset(); }\n')
        f.write('            if (dbg2_writer) { dbg2_writer->close(); dbg2_writer.reset(); }\n')
        f.write('            if (dbg3_file.is_open()) dbg3_file.close();\n')
        f.write('        }\n')
        f.write('        OutputFormat requested_fmt = static_cast<OutputFormat>(CntrPar.OutputFormat);\n')
        f.write('        OutputFormat fmt = DebugWriter::effective_format(requested_fmt);\n')
        f.write('        if (requested_fmt == OutputFormat::HDF5 && fmt != OutputFormat::HDF5) {\n')
        f.write('            fprintf(stderr, "ROSCO WARNING: HDF5 output requested but this build has no HDF5 support; writing text debug files.\\n");\n')
        f.write('        }\n')
        f.write('\n')

        # .dbg writer init
        f.write('        if (CntrPar.LoggingLevel > 0) {\n')
        f.write('            dbg_writer = DebugWriter::create(fmt);\n')
        f.write('            std::string dbg_path = (fmt == OutputFormat::HDF5)\n')
        f.write('                ? root + ".RO.h5" : root + ".RO.dbg";\n')
        f.write('            dbg_writer->open(dbg_path, DebugOutStrings, DebugOutUnits, nDebugOuts);\n')
        f.write('        }\n')
        f.write('\n')

        # .dbg2 writer init
        f.write('        if (CntrPar.LoggingLevel > 1) {\n')
        f.write('            dbg2_writer = DebugWriter::create(fmt);\n')
        f.write('            std::string dbg2_path = (fmt == OutputFormat::HDF5)\n')
        f.write('                ? root + ".RO.dbg2.h5" : root + ".RO.dbg2";\n')
        f.write('            dbg2_writer->open(dbg2_path, LocalVarOutStrings, LocalVarOutUnits, nLocalVars);\n')
        f.write('        }\n')
        f.write('\n')

        # .dbg3 file init (stays text for now)
        f.write('        if (CntrPar.LoggingLevel > 2) {\n')
        f.write('            avr_indices.clear();\n')
        f.write('            int avrBaseLength = 85;\n')
        f.write('            for (int i = 1; i <= avrBaseLength; i++) {\n')
        f.write('                avr_indices.push_back(i);\n')
        f.write('            }\n')
        f.write('            if (CntrPar.CC_Mode > 0) {\n')
        f.write('                for (int i = 0; i < (int)CntrPar.CC_GroupIndex.size(); i++) {\n')
        f.write('                    avr_indices.push_back(CntrPar.CC_GroupIndex[i]);\n')
        f.write('                    avr_indices.push_back(CntrPar.CC_GroupIndex[i] + 1);\n')
        f.write('                }\n')
        f.write('            }\n')
        f.write('            if (CntrPar.StC_Mode > 0) {\n')
        f.write('                for (int i = 0; i < (int)CntrPar.StC_GroupIndex.size(); i++) {\n')
        f.write('                    avr_indices.push_back(CntrPar.StC_GroupIndex[i]);\n')
        f.write('                }\n')
        f.write('            }\n')
        f.write('            std::string dbg3_path = root + ".RO.dbg3";\n')
        f.write('            dbg3_file.open(dbg3_path);\n')
        f.write('            dbg3_file << "\\n\\n\\n\\n\\n\\n";\n')
        f.write('            char buf[32];\n')
        f.write('            snprintf(buf, sizeof(buf), "%21s", "LocalVar%Time ");\n')
        f.write('            dbg3_file << buf;\n')
        f.write('            for (size_t i = 0; i < avr_indices.size(); i++) {\n')
        f.write('                snprintf(buf, sizeof(buf), "            AvrSWAP(%4d)", avr_indices[i]);\n')
        f.write('                dbg3_file << buf;\n')
        f.write('            }\n')
        f.write('            dbg3_file << "\\n";\n')
        f.write('            snprintf(buf, sizeof(buf), "%21s", "(s)");\n')
        f.write('            dbg3_file << buf;\n')
        f.write('            for (size_t i = 0; i < avr_indices.size(); i++) {\n')
        f.write('                snprintf(buf, sizeof(buf), "%22s", "(-)");\n')
        f.write('                dbg3_file << buf;\n')
        f.write('            }\n')
        f.write('            dbg3_file << "\\n";\n')
        f.write('        }\n')
        f.write('    }\n')
        f.write('\n')

        # --- Console output ---
        f.write('    // --- Console output every 10 seconds ---\n')
        f.write('    if (std::fmod(LocalVar.Time, 10.0) == 0.0) {\n')
        f.write('        printf("Generator speed: %6.1f RPM, Pitch angle: %5.1f deg, Power: %7.1f kW, Est. wind Speed: %5.1f m/s\\n",\n')
        f.write('               LocalVar.GenSpeedF * RPS2RPM,\n')
        f.write('               LocalVar.BlPitch[0] * R2D,\n')
        f.write('               (double)avrSWAP[14] / 1000.0,\n')
        f.write('               LocalVar.WE_Vw);\n')
        f.write('    }\n')
        f.write('\n')

        # --- Clamping ---
        f.write('    // --- Clamp debug data ---\n')
        f.write('    for (int i = 0; i < nDebugOuts; i++) {\n')
        f.write('        DebugOutData[i] = clamp_debug(DebugOutData[i]);\n')
        f.write('    }\n')
        f.write('    if (CntrPar.LoggingLevel > 1) {\n')
        f.write('        for (int i = 0; i < nLocalVars; i++) {\n')
        f.write('            LocalVarOutData[i] = clamp_debug(LocalVarOutData[i]);\n')
        f.write('        }\n')
        f.write('    }\n')
        f.write('\n')

        # --- Write rows via DebugWriter ---
        f.write('    // --- Write debug data ---\n')
        f.write('    if (LocalVar.n_DT % CntrPar.n_DT_Out == 0) {\n')
        f.write('        if (CntrPar.LoggingLevel > 0 && LocalVar.iStatus >= 0 && dbg_writer) {\n')
        f.write('            dbg_writer->write_row(LocalVar.Time, DebugOutData, nDebugOuts);\n')
        f.write('        }\n')
        f.write('        if (CntrPar.LoggingLevel > 1 && LocalVar.iStatus >= 0 && dbg2_writer) {\n')
        f.write('            dbg2_writer->write_row(LocalVar.Time, LocalVarOutData, nLocalVars);\n')
        f.write('        }\n')
        f.write('        if (CntrPar.LoggingLevel > 2 && LocalVar.iStatus >= 0) {\n')
        f.write('            char buf[32];\n')
        f.write('            snprintf(buf, sizeof(buf), "%20.5f", LocalVar.Time);\n')
        f.write('            dbg3_file << buf;\n')
        f.write('            for (size_t i = 0; i < avr_indices.size(); i++) {\n')
        f.write('                double val = (double)avrSWAP[avr_indices[i] - 1];\n')
        f.write('                val = clamp_debug(val);\n')
        f.write('                dbg3_file << "     ";\n')
        f.write('                snprintf(buf, sizeof(buf), "%20.5E", val);\n')
        f.write('                dbg3_file << buf;\n')
        f.write('            }\n')
        f.write('            dbg3_file << "\\n";\n')
        f.write('        }\n')
        f.write('    }\n')
        f.write('\n')

        # --- Close writers ---
        f.write('    // --- Close writers on shutdown ---\n')
        f.write('    if (LocalVar.iStatus == -1) {\n')
        f.write('        if (dbg_writer) { dbg_writer->close(); dbg_writer.reset(); }\n')
        f.write('        if (dbg2_writer) { dbg2_writer->close(); dbg2_writer.reset(); }\n')
        f.write('        if (dbg3_file.is_open()) dbg3_file.close();\n')
        f.write('    }\n')
        f.write('}\n')


def _write_toml_template(yfile):
    """Generate Examples/DISCON_template.toml"""
    reg = load_yaml(yfile)
    reg.pop('default_types', None)
    params = reg['ControlParameters']

    sections = _extract_sections(yfile, 'ControlParameters')

    # DISCON_template.toml goes next to existing DISCON.IN examples
    examples_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))),
        'Examples')
    out_path = os.path.join(examples_dir, 'DISCON_template.toml')

    with open(out_path, 'w') as f:
        f.write('# ROSCO Controller Configuration — TOML format\n')
        f.write('# AUTO-GENERATED template from rosco_types.yaml\n')
        f.write('# Edit this file to configure your controller.\n')
        f.write('# Array parameters: use TOML native array syntax, e.g. PC_GS_angles = [0.1, 0.2, 0.3]\n')
        f.write('# Count scalars (PC_GS_n, VS_n, etc.) are derived from array length — omit them.\n')
        f.write('\n')

        prev_section = None
        for name, param in params.items():
            cpp_type, is_2d = _cpp_type(param)
            if cpp_type is None:
                continue
            ptype  = param.get('type', '')
            alloc  = param.get('allocatable', False)

            section = sections.get(name)
            if section and section != prev_section:
                f.write(f'\n# ===== {section} =====\n')
                prev_section = section

            desc = (param.get('description') or '').strip()
            if desc:
                f.write(f'# {desc}\n')

            eq = param.get('equals')

            if alloc:
                if is_2d:
                    f.write(f'# {name} = [[...], [...]]  # 2D array (rows x cols)\n')
                else:
                    f.write(f'# {name} = []  # array\n')
            elif ptype == 'character':
                val = f'"{eq}"' if eq else '""'
                f.write(f'{name} = {val}\n')
            elif cpp_type == 'double':
                val = eq if eq is not None else 0.0
                f.write(f'{name} = {val}\n')
            elif cpp_type == 'int':
                val = eq if eq is not None else 0
                f.write(f'{name} = {val}\n')
            else:
                f.write(f'# {name} = ...\n')


if __name__ == '__main__':
    fname = os.path.join(os.path.dirname(os.path.abspath(__file__)),'rosco_types.yaml')
    generate(fname)
